gcp_project_id = "My Project 87866"
service_account_email = "dina-694@encoded-yen-425611-v1.iam.gserviceaccount.com"
region =  "us-central1"
zone = "us-central1-c"
vm_name = "tf-gcp-vm"
vm_type = "n1-standard-1"
vm_image = "centos-cloud/centos-7"
vm_image_type = "pd-standard"